server:
  port: 8082

# druid配置
spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloudlibrary
      username: root
      password: jy010711
  redis:
    host: localhost
    port: 6379
    password: jy010711
    lettuce:
      pool:
        max-active: 8
        max-idle: 8 # 最大空闲连接数
        min-idle: 0
        max-wait: 1000
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

